add postStart hook to strapi to register admin

diff --git a/microservices/strapi/dev-public-catalog/values.yaml b/microservices/strapi/dev-public-catalog/values.yaml
--- a/microservices/strapi/dev-public-catalog/values.yaml
+++ b/microservices/strapi/dev-public-catalog/values.yaml
@@ -59,11 +59,10 @@ deployment:
     JWT_SECRET: "public-catalog-strapi-standard-users-jwt-key.value"
     ENCRYPTION_KEY: "public-catalog-strapi-encryption-key.value"
     GH_WORKFLOW_TOKEN: "public-catalog-strapi-gh-workflow-token.value"
-    STRAPI_ADMIN_USERNAME: "public-catalog-strapi-admin-user.username"
-    STRAPI_ADMIN_PASSWORD: "public-catalog-strapi-admin-user.password"
-    STRAPI_ADMIN_FIRSTNAME: "public-catalog-strapi-admin-user.firstname"
-    STRAPI_ADMIN_LASTNAME: "public-catalog-strapi-admin-user.lastname"
-    STRAPI_ADMIN_EMAIL: "public-catalog-strapi-admin-user.email"
+    STRAPI_ADMIN_EMAIL: "public-catalog-strapi-app-admin-user.email"
+    STRAPI_ADMIN_PASSWORD: "public-catalog-strapi-app-admin-user.password"
+    STRAPI_ADMIN_FIRSTNAME: "public-catalog-strapi-app-admin-user.firstname"
+    STRAPI_ADMIN_LASTNAME: "public-catalog-strapi-app-admin-user.lastname"
 
   postStartHook:
     create: true
@@ -73,7 +72,7 @@ deployment:
       - |
         echo "Waiting for Strapi to be ready..."
         timeout 300 sh -c '
-          until wget -q --spider http://interop-public-catalog-strapi:1337/admin/init; do
+          until wget -q --spider http://interop-public-catalog-strapi:1337/admin/register-admin; do
             echo "Strapi is not ready yet..."
             sleep 2
           done
@@ -81,20 +80,18 @@ deployment:
         echo "Strapi is ready!"
         echo "Registering admin if not exists..."
 
-        http_code=$(wget -q --server-response --method=POST --header="Content-Type: application/json" --body-data="{
-          \"username\": \"${STRAPI_ADMIN_USERNAME}\",
-          \"password\": \"${STRAPI_ADMIN_PASSWORD}\",
-          \"firstname\": \"${STRAPI_ADMIN_FIRSTNAME}\",
-          \"lastname\": \"${STRAPI_ADMIN_LASTNAME}\",
-          \"email\": \"${STRAPI_ADMIN_EMAIL}\",
-          \"blocked\": false,
-          \"isActive\": true
-        }" -O /tmp/strapi-admin-registration-response.json http://interop-public-catalog-strapi:1337/admin/auth/local/register 2>&1 | awk "/HTTP\// {print \$2}" | tail -1)
+        HTTP_CODE=$(wget --server-response --header="Content-Type: application/json" --post-data="{
+          \"email\":\"${STRAPI_ADMIN_EMAIL}\",
+          \"password\":\"${STRAPI_ADMIN_PASSWORD}\",
+          \"firstname\":\"${STRAPI_ADMIN_FIRSTNAME}\",
+          \"lastname\":\"${STRAPI_ADMIN_LASTNAME}\"
+        }" http://interop-public-catalog-strapi:1337/admin/register-admin -O - 2>&1 | grep "HTTP/" | tail -1 | sed -E 's/.*HTTP\/[0-9.]+ ([0-9]+).*/\1/'
 
-        if [ "$http_code" = "200" ]; then
-          echo "Admin registered successfully!"
+        if [ "$HTTP_CODE" = "200" ]; then
+          echo "Admin registered successfully. HTTP code: $HTTP_CODE."
+        elif [ "$HTTP_CODE" = "400" ]; then
+          echo "Admin already exists. No action needed. HTTP code: $HTTP_CODE."
         else
-          echo "Admin registration failed."
-          echo "Response code: $http_code. Response body:"
-          cat /tmp/strapi-admin-registration-response.json
+          echo "An error occurred during admin registration. HTTP code: $HTTP_CODE."
+          exit 1
         fi
